### ISSUE TITLE
Error 7 

### ISSUE THREAD

**Issue by hmolina3** [wialon/php-wialon#4]
Hello, thanks you for attention,

I have the problem withe the next code:
```php
<?
	$result = $wialon_api->login($token);
	$json = json_decode($result, true);
	echo $json['user']['nm'];
	if(!isset($json['error'])){
		//echo $wialon_api->core_get_account_data('{"type":1}'); // this command run ok
		echo $wialon_api->core_search_item('{"id":717359,"flags":1}'); //this command always say error 7
													//if i use the hex format in flags, the system return error 4
		//echo "si entre ";
		$wialon_api->logout();
		//echo " sali";
	} else {
		echo WialonError::error($json['error']);
	}
?>
```

I probe the next line withe my token and code run ok, return me the parameters in JSON format, its ok.
`echo $wialon_api->core_get_account_data('{"type":1}');`

But when i run the next command, always return me error 7.
`echo $wialon_api->core_search_item('{"id":717359,"flags":1}');`

**Comment by ashmigelski** [comment]
Hey @hmolina3

[core/search_item](https://sdk.wialon.com/wiki/en/sidebar/remoteapi/apiref/core/search_item) method try tto get data from wialon DB by ID. If you have no access to this item you'll get `{error:7}`.

You should use core/search_item only when you're sure item with ID exists and you have access to it. If you are not sure - try to send [core/search_items](https://sdk.wialon.com/wiki/en/sidebar/remoteapi/apiref/core/search_items) first and you'll get at available items in response. We have sample of core/search_items usage in our docs: https://sdk.wialon.com/wiki/en/sidebar/remoteapi/codesamples/search#search_items_by_property

Also you can visit our [forum](https://forum.gurtam.com/viewforum.php?id=59) and find some useful info there

**Comment by hmolina3** [comment]
thanks, that was the solution.
I was not sure about the ID, but with this is work now

**Comment by hmolina3** [comment]
thanks, that was the solution.
I was not sure about the ID, but with this is work now
